name="Jim"
favmod=1
favteam=1
favmap="ns_hera"
skill=90
spray="chick1"
gorge_percent=10
lerk_percent=20
fade_percent=88
onos_percent=99
numgames=0
hal_pretrain_file="common_hal.trn"
hal_aux_file="common_hal.aux"
hal_ban_file="common_hal.ban"
hal_swap_file="common_hal.swp"

#
# Prefered model for each bot.
# Don't use this for TDM gameplays
# or the bots will cause unbalanced teams

#model=helmet

#
# aim_skill = 0.0 to 1.0
# ------------------
# 0.0 is normal old rcbot aiming
# 1.0 is dead on precision
#
# I'd make this slightly more than 0.0 but not much

aim_skill=0.2

#
# time = 0.0 to infinity (make it something useful!)
# --------------------------------------------------
# time in seconds for bot to update its aiming offset
# the less time then the more dead on its aiming will
# be even if the target is accelerating

aim_time=1.0;

#
# the speed is the fraction of 10 degrees per frame
# the old rcbot was 2 degrees per frame
# so the higher you make this then the faster the bot
# will move its aiming
# this value now is just a bit better than the old rcbot
# aiming

aim_speed=0.25
