config commanding 0
config wait_for_orders 0
config dont_shoot 0
config chatting 0
config real_mode 0
config max_bots 10
config min_bots 0
config gorge_amount 0.5
config update_ladder_time 0.0
# Welcome messege and tooltips
config tooltips 1
# max path revs, the lower the setting
# the better CPU performance in the
# path finding algorithm, but it takes
# longer to find paths.
config max_path_revs 150
# update vision revs, time to update what
# the bot can see, as it is quite cpu
# intensive you can change these values 
# depending on cpu speed.
config max_update_vision_revs 200
# The time for this bot to update a number of entities
# in the game to add to their visible list
# Increasing this will increase bots reaction time
config update_vision_time 0.01
# dont reserve bot slots
config reserve_bot_slots 0
# bots old chat chance
config chat_percent 80
# bots reply chat chance using megahal
config chat_reply_percent 85
# keep bots learning their chatting skills
config chat_dont_learn 0
# bots try to balance teams
config balance_teams 1
# reply to bots too
config chat_reply_to_bots 0
# allow bot cam (may run slightly slower)
# (needs to work out stuff in game)
config allow_botcam 0
# control the bots to learn on using weapons
config disable_weapon_learning 0
# bots dont make squads
config disable_bot_squads 0
#TS Mod Specific Cvars
config ts_dont_steal_weapons 0
config ts_dont_pickup_weapons 0
# bots only use Kung Fu Fighting, like Carl Douglas haha!
config ts_kungfu 0
#NS Mod Specific Cvars
# dont build ip at NS start
config marine_auto_build 0
#config not_ns3final 0


# Optional settings, remove # tags to use...

# My (madmax2) prefered setting for ladder climbing, may help bots wiggle free from sticky ladders
# config update_ladder_time 0.2

# If bot gets hopelessly stuck, it may suicide a bit faster, increase to 50 for quicker suicides
# config bot_stuck_speed 30

# On a listenserver, could bind keys to "exec xxxx.cfg" with "rcbot config sc_breakable_classes_ally"
# with or without the 0, to turn on and off, or make a map.cfg for every map with it on or off
# see included polar_rescue.cfg in the map_configs folder for example cvar syntax
